name: isail
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.19.0
  flutter_pdfview: ^1.0.4
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.6
  path_provider: ^2.1.5
  flutter_local_notifications: ^9.0.0+1  # Specify the dependency without platform-specific constraints
  timezone: ^0.8.0
  logging: ^1.0.0  # Add logging package
  image_picker: ^0.8.4+4
  file_picker: ^8.0.6
  share_plus: ^4.0.10
  flutter_gen: ^5.9.0
  html: ^0.15.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.8.10 # Add intl_utils package

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/welcome_background.jpg
    - assets/documents/document1.pdf
    - assets/documents/document2.pdf
    - assets/documents/document3.pdf
    - assets/documents/document4.pdf
    - assets/documents/document5.pdf
    - assets/documents/document6.pdf
    - assets/documents/document7.pdf
    - assets/documents/document8.pdf
    - assets/documents/document9.pdf
    - assets/documents/document10.pdf
    - assets/documents/document11.pdf
    - assets/documents/document12.pdf
    - assets/documents/document13.pdf
    - assets/documents/document14.pdf
    - assets/documents/document15.pdf
    - assets/documents/document16.pdf
    - assets/documents/document17.pdf
    - assets/documents/document18.pdf

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated